Update README.md
Odzen/barber_management_frontend pull request #23
Opened 2023-06-04 20:09 UTC by SantiagoEsquivelHub

2023-06-04 21:21 UTC, Odzen requested changes

2023-06-04 21:21 UTC, Odzen commented on README.md
> +3. [ci.yml](https://github.com/Odzen/barber_management_frontend/tree/main/.github/workflows/ci.yml) - This workflow runs on every push or pull request (opened, synchronize) to main branch in the repo
Aquí te falta un paso. Deploy. Deberías de explicar un poco ese paso, es bastante importante, porque es el encargado de crear el branch deploy para el "QA" a través de un script customizado, cada vez que se abre una PR.

2023-06-04 21:21 UTC, Odzen commented on README.md
> +2. [notifications.yml](https://github.com/Odzen/barber_management_frontend/tree/main/.github/workflows/notifications.yml) - This action runs on every push to the main branch. It sends a notification
Creo el link de esto está roto.

2023-06-04 21:21 UTC, Odzen commented on README.md
> +6. [cached_install/action.yml](https://github.com/Odzen/barber_management_frontend/tree/main/.github/cached_install/action.yml) - This action configures Node.js, caches the node_modules modules, and
Creo el link de esto está roto.

2023-06-04 23:03 UTC, SantiagoEsquivelHub commented on README.md
> +6. [cached_install/action.yml](https://github.com/Odzen/barber_management_frontend/tree/main/.github/cached_install/action.yml) - This action configures Node.js, caches the node_modules modules, and
Corregido

2023-06-04 23:05 UTC, SantiagoEsquivelHub commented on README.md
> +2. [notifications.yml](https://github.com/Odzen/barber_management_frontend/tree/main/.github/workflows/notifications.yml) - This action runs on every push to the main branch. It sends a notification
Corregido

2023-06-04 23:10 UTC, SantiagoEsquivelHub commented on README.md
> +3. [ci.yml](https://github.com/Odzen/barber_management_frontend/tree/main/.github/workflows/ci.yml) - This workflow runs on every push or pull request (opened, synchronize) to main branch in the repo
Realizado

2023-06-05 00:04 UTC, Odzen approved these changes

2023-06-05 00:13 UTC, merged