US LR 001
Odzen/barber_management_frontend pull request #8
Opened 2023-04-23 22:51 UTC by SantiagoEsquivelHub

2023-04-23 23:00 UTC, SantiagoEsquivelHub commented
No lo aceptes todavía @Odzen, tengo que actualizar la rama con respecto a Dev

2023-04-26 05:08 UTC, Odzen requested changes
Me parece buen trabajo. El único comentario a parte de los "enum" es que el responsive en pantallas demasiado pequeñas como 320 px de ancho, se rompe un poco. Pero como este caso es extremo, no importa tampoco mucho..

2023-04-26 05:08 UTC, Odzen commented on src/containers/mainRouter/index.jsx
> +  if (role == 'Barber' && location.pathname === '/') {
Me gustaría que estos roles estén en un archivo enum.js en alguna carpeta de utils/

Algo así:

```
export const Roles = Object.freeze({
	ADMIN: 'admin',
	BARBER: 'barber',
	...
});
```

Y así poder hacer las verificaciones de roles. Lo de arriba solo es un ejemplo, la idea es que estén igual a los rolens del enum de prisma

2023-04-26 05:10 UTC, SantiagoEsquivelHub commented on src/containers/mainRouter/index.jsx
> +  if (role == 'Barber' && location.pathname === '/') {
Listo, me parece bien

2023-04-26 21:03 UTC, merged